name: Feature request
description: Submit suggestions for new features or improvements to enhance the software's capabilities and user experience.
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you are requesting.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: preferable-solution
    attributes:
      label: Preferable solution
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
